import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme-provider";
const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "ChatChit",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={font.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem={false}
                    storageKey="chatchit-theme"
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
