import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme-provider";
import ReduxProvider from "@/components/providers/redux-provider";
import { Toaster } from "@/components/ui/toaster";
import TanstackProvider from "@/components/providers/tanstack-provider";
const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "ChatChit",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={font.className}>
                <main>
                    <ReduxProvider>
                        <TanstackProvider>
                            <ThemeProvider
                                attribute="class"
                                defaultTheme="dark"
                                enableSystem={false}
                                storageKey="chatchit-theme"
                            >
                                {children}
                            </ThemeProvider>
                            <Toaster />
                        </TanstackProvider>
                    </ReduxProvider>
                </main>
            </body>
        </html>
    );
}
